-- =================================================================
-- Migration 007 (Phase 5B): Seed system roles and permissions
-- down_revision: 006_5B
-- Transaction: yes
-- Source: 5B §33.4 (using §34.1 numbering — 007 = seed)
-- Note: uses name-based lookups (ON CONFLICT DO NOTHING) for
--       idempotency; NOT the hardcoded-UUID §33.4 variant which
--       conflicts with the inline migration boundaries.
-- =================================================================

-- System roles (organization_id IS NULL = platform-global)
INSERT INTO organization.roles (id, organization_id, name, display_name, description, is_system, is_active)
VALUES
  ('018c0000-0000-7000-a000-000000000001'::UUID, NULL, 'OWNER',        'Owner',         'Full organization control and ownership',      TRUE, TRUE),
  ('018c0000-0000-7000-a000-000000000002'::UUID, NULL, 'ADMIN',        'Admin',         'Administrative access to most features',       TRUE, TRUE),
  ('018c0000-0000-7000-a000-000000000003'::UUID, NULL, 'MEMBER',       'Member',        'Standard operational member access',           TRUE, TRUE),
  ('018c0000-0000-7000-a000-000000000004'::UUID, NULL, 'BILLING_ADMIN','Billing Admin', 'Billing, invoices, and financial management',  TRUE, TRUE),
  ('018c0000-0000-7000-a000-000000000005'::UUID, NULL, 'VIEWER',       'Viewer',        'Read-only access to approved resources',       TRUE, TRUE)
ON CONFLICT (name) WHERE organization_id IS NULL DO NOTHING;

-- System permissions
INSERT INTO organization.permissions (name, display_name, resource, action) VALUES
  ('organization:read','View Organization','organization','read'),
  ('organization:update','Edit Organization Settings','organization','update'),
  ('organization:suspend','Suspend Organization','organization','suspend'),
  ('organization:delete','Delete Organization','organization','delete'),
  ('member:read','View Members','member','read'),
  ('member:invite','Invite Members','member','invite'),
  ('member:remove','Remove Members','member','remove'),
  ('member:suspend','Suspend Members','member','suspend'),
  ('role:read','View Roles','role','read'),
  ('role:manage','Manage Roles','role','manage'),
  ('agent:read','View Agents','agent','read'),
  ('agent:write','Edit Agents','agent','write'),
  ('agent:publish','Publish Agents','agent','publish'),
  ('agent:delete','Delete Agents','agent','delete'),
  ('call:read','View Calls','call','read'),
  ('call:initiate','Initiate Calls','call','initiate'),
  ('call:transfer','Transfer Calls','call','transfer'),
  ('call:record','Configure Recording','call','record'),
  ('contact:read','View Contacts','contact','read'),
  ('contact:write','Edit Contacts','contact','write'),
  ('contact:delete','Delete Contacts','contact','delete'),
  ('contact:merge','Merge Contacts','contact','merge'),
  ('contact:convert','Convert Leads','contact','convert'),
  ('deal:read','View Deals','deal','read'),
  ('deal:write','Edit Deals','deal','write'),
  ('deal:close','Close Deals','deal','close'),
  ('campaign:read','View Campaigns','campaign','read'),
  ('campaign:write','Edit Campaigns','campaign','write'),
  ('campaign:start','Start Campaigns','campaign','start'),
  ('campaign:stop','Stop Campaigns','campaign','stop'),
  ('knowledge:read','View Knowledge Bases','knowledge','read'),
  ('knowledge:write','Edit Knowledge Bases','knowledge','write'),
  ('knowledge:delete','Delete Knowledge Bases','knowledge','delete'),
  ('workflow:read','View Workflows','workflow','read'),
  ('workflow:write','Edit Workflows','workflow','write'),
  ('workflow:publish','Publish Workflows','workflow','publish'),
  ('prompt:read','View Prompts','prompt','read'),
  ('prompt:write','Edit Prompts','prompt','write'),
  ('prompt:publish','Publish Prompts','prompt','publish'),
  ('prompt:rollback','Rollback Prompts','prompt','rollback'),
  ('billing:read','View Billing','billing','read'),
  ('billing:manage','Manage Billing','billing','manage'),
  ('invoice:read','View Invoices','invoice','read'),
  ('analytics:read','View Analytics','analytics','read'),
  ('analytics_cost:read','View Cost Analytics','analytics_cost','read'),
  ('analytics_platform:read','View Platform Analytics','analytics_platform','read'),
  ('integration:read','View Integrations','integration','read'),
  ('integration:manage','Manage Integrations','integration','manage'),
  ('webhook:read','View Webhooks','webhook','read'),
  ('webhook:manage','Manage Webhooks','webhook','manage'),
  ('plugin:read','View Plugins','plugin','read'),
  ('plugin:install','Install Plugins','plugin','install'),
  ('plugin:manage','Manage Plugins','plugin','manage'),
  ('api_key:read','View API Keys','api_key','read'),
  ('api_key:manage','Manage API Keys','api_key','manage'),
  ('audit:read','View Audit Log','audit','read'),
  ('suppression:read','View Suppressions','suppression','read'),
  ('suppression:manage','Manage Suppressions','suppression','manage'),
  ('suppression:lift','Lift Suppressions','suppression','lift'),
  ('consent:read','View Consent Records','consent','read'),
  ('consent:manage','Manage Consent','consent','manage'),
  ('compliance:read','View Compliance Policy','compliance','read'),
  ('compliance:manage','Manage Compliance Policy','compliance','manage'),
  ('data_subject:manage','Handle Data Subject Requests','data_subject','manage'),
  ('tax:manage','Manage Tax Profile','tax','manage'),
  ('recording:read','Access Recordings','recording','read'),
  ('recording:delete','Delete Recordings','recording','delete'),
  ('transcript:read','View Transcripts','transcript','read')
ON CONFLICT (name) DO NOTHING;

-- Role-permission assignments
WITH
  r AS (SELECT id, name FROM organization.roles WHERE organization_id IS NULL),
  p AS (SELECT id, name FROM organization.permissions)
INSERT INTO organization.role_permissions (id, role_id, permission_id)
SELECT gen_uuid_v7(), r.id, p.id
FROM (VALUES
  ('OWNER','organization:read'),('OWNER','organization:update'),('OWNER','organization:suspend'),('OWNER','organization:delete'),
  ('OWNER','member:read'),('OWNER','member:invite'),('OWNER','member:remove'),('OWNER','member:suspend'),
  ('OWNER','role:read'),('OWNER','role:manage'),
  ('OWNER','agent:read'),('OWNER','agent:write'),('OWNER','agent:publish'),('OWNER','agent:delete'),
  ('OWNER','call:read'),('OWNER','call:initiate'),('OWNER','call:transfer'),('OWNER','call:record'),
  ('OWNER','contact:read'),('OWNER','contact:write'),('OWNER','contact:delete'),('OWNER','contact:merge'),('OWNER','contact:convert'),
  ('OWNER','deal:read'),('OWNER','deal:write'),('OWNER','deal:close'),
  ('OWNER','campaign:read'),('OWNER','campaign:write'),('OWNER','campaign:start'),('OWNER','campaign:stop'),
  ('OWNER','knowledge:read'),('OWNER','knowledge:write'),('OWNER','knowledge:delete'),
  ('OWNER','workflow:read'),('OWNER','workflow:write'),('OWNER','workflow:publish'),
  ('OWNER','prompt:read'),('OWNER','prompt:write'),('OWNER','prompt:publish'),('OWNER','prompt:rollback'),
  ('OWNER','billing:read'),('OWNER','billing:manage'),('OWNER','invoice:read'),
  ('OWNER','analytics:read'),('OWNER','analytics_cost:read'),
  ('OWNER','integration:read'),('OWNER','integration:manage'),
  ('OWNER','webhook:read'),('OWNER','webhook:manage'),
  ('OWNER','plugin:read'),('OWNER','plugin:install'),('OWNER','plugin:manage'),
  ('OWNER','api_key:read'),('OWNER','api_key:manage'),('OWNER','audit:read'),
  ('OWNER','suppression:read'),('OWNER','suppression:manage'),('OWNER','suppression:lift'),
  ('OWNER','consent:read'),('OWNER','consent:manage'),
  ('OWNER','compliance:read'),('OWNER','compliance:manage'),
  ('OWNER','data_subject:manage'),('OWNER','tax:manage'),
  ('OWNER','recording:read'),('OWNER','recording:delete'),('OWNER','transcript:read'),
  ('ADMIN','organization:read'),('ADMIN','organization:update'),
  ('ADMIN','member:read'),('ADMIN','member:invite'),('ADMIN','member:remove'),('ADMIN','member:suspend'),
  ('ADMIN','role:read'),('ADMIN','role:manage'),
  ('ADMIN','agent:read'),('ADMIN','agent:write'),('ADMIN','agent:publish'),('ADMIN','agent:delete'),
  ('ADMIN','call:read'),('ADMIN','call:initiate'),('ADMIN','call:transfer'),('ADMIN','call:record'),
  ('ADMIN','contact:read'),('ADMIN','contact:write'),('ADMIN','contact:delete'),('ADMIN','contact:merge'),('ADMIN','contact:convert'),
  ('ADMIN','deal:read'),('ADMIN','deal:write'),('ADMIN','deal:close'),
  ('ADMIN','campaign:read'),('ADMIN','campaign:write'),('ADMIN','campaign:start'),('ADMIN','campaign:stop'),
  ('ADMIN','knowledge:read'),('ADMIN','knowledge:write'),('ADMIN','knowledge:delete'),
  ('ADMIN','workflow:read'),('ADMIN','workflow:write'),('ADMIN','workflow:publish'),
  ('ADMIN','prompt:read'),('ADMIN','prompt:write'),('ADMIN','prompt:publish'),('ADMIN','prompt:rollback'),
  ('ADMIN','billing:read'),('ADMIN','invoice:read'),
  ('ADMIN','analytics:read'),('ADMIN','analytics_cost:read'),
  ('ADMIN','integration:read'),('ADMIN','integration:manage'),
  ('ADMIN','webhook:read'),('ADMIN','webhook:manage'),
  ('ADMIN','plugin:read'),('ADMIN','plugin:install'),('ADMIN','plugin:manage'),
  ('ADMIN','api_key:read'),('ADMIN','api_key:manage'),('ADMIN','audit:read'),
  ('ADMIN','suppression:read'),('ADMIN','suppression:manage'),('ADMIN','suppression:lift'),
  ('ADMIN','consent:read'),('ADMIN','consent:manage'),
  ('ADMIN','compliance:read'),('ADMIN','compliance:manage'),
  ('ADMIN','data_subject:manage'),
  ('ADMIN','recording:read'),('ADMIN','recording:delete'),('ADMIN','transcript:read'),
  ('MEMBER','organization:read'),('MEMBER','member:read'),('MEMBER','role:read'),
  ('MEMBER','agent:read'),('MEMBER','agent:write'),
  ('MEMBER','call:read'),('MEMBER','call:initiate'),('MEMBER','call:transfer'),
  ('MEMBER','contact:read'),('MEMBER','contact:write'),('MEMBER','contact:convert'),
  ('MEMBER','deal:read'),('MEMBER','deal:write'),
  ('MEMBER','campaign:read'),('MEMBER','campaign:write'),
  ('MEMBER','knowledge:read'),('MEMBER','knowledge:write'),
  ('MEMBER','workflow:read'),('MEMBER','workflow:write'),
  ('MEMBER','prompt:read'),('MEMBER','prompt:write'),
  ('MEMBER','analytics:read'),
  ('MEMBER','integration:read'),('MEMBER','webhook:read'),('MEMBER','plugin:read'),
  ('MEMBER','suppression:read'),('MEMBER','consent:read'),('MEMBER','consent:manage'),
  ('MEMBER','recording:read'),('MEMBER','transcript:read'),
  ('BILLING_ADMIN','organization:read'),('BILLING_ADMIN','member:read'),
  ('BILLING_ADMIN','billing:read'),('BILLING_ADMIN','billing:manage'),('BILLING_ADMIN','invoice:read'),
  ('BILLING_ADMIN','analytics:read'),('BILLING_ADMIN','analytics_cost:read'),('BILLING_ADMIN','tax:manage'),
  ('VIEWER','organization:read'),('VIEWER','member:read'),('VIEWER','role:read'),
  ('VIEWER','agent:read'),('VIEWER','call:read'),
  ('VIEWER','contact:read'),('VIEWER','deal:read'),
  ('VIEWER','campaign:read'),('VIEWER','knowledge:read'),
  ('VIEWER','workflow:read'),('VIEWER','prompt:read'),
  ('VIEWER','analytics:read'),
  ('VIEWER','integration:read'),('VIEWER','webhook:read'),('VIEWER','plugin:read'),
  ('VIEWER','recording:read'),('VIEWER','transcript:read')
) AS m(role_name, perm_name)
JOIN r ON r.name = m.role_name
JOIN p ON p.name = m.perm_name
ON CONFLICT (role_id, permission_id) DO NOTHING;
